#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# only run on added/modified files
git diff --name-only --cached --diff-filter=AM -- "*.js" | \
while read -r file 
do
  if [ -f "$file" ]; then # don't run on deleted files
    npm run lint "$file"
  fi
done
